# Generated by Django 5.1.7 on 2025-04-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='hobbies',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='infoextra',
            name='sports',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
