# Generated by Django 5.2 on 2025-04-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_producto', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=20)),
            ],
        ),
    ]
