# Generated by Django 5.1.7 on 2025-04-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_carga',
            field=models.DateField(null=True),
        ),
    ]
